# Generated by Django 4.2.3 on 2023-08-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='publicaciones_favoritas',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
